import { $, $$, esc, fmtDate, fmtDuration, login, logout, requireSession, supabase, invoke, toast, setLoading, openModal, closeModal, setupModal, setupSidebar, emptyState, skeleton, scoreBadge, initials, isConfigured } from './core.js';

const nav=[['dashboard','⌂','Beranda'],['learn','▤','Belajar'],['mini','◫','Mini Tryout'],['tryout','◷','Tryout'],['progress','↗','Progres'],['history','≡','Riwayat']];
let state={profile:null,route:'dashboard',params:new URLSearchParams(),attempt:null,current:0,timer:null};

function renderNav(){
  const item=([id,icon,label])=>`<button class="nav-item ${state.route===id?'active':''}" data-route="${id}"><span class="nav-icon">${icon}</span><span>${label}</span></button>`;
  $('#desktop-nav').innerHTML=nav.map(item).join(''); $('#mobile-nav').innerHTML=nav.slice(0,5).map(item).join('');
  $$('[data-route]').forEach(el=>el.onclick=()=>go(el.dataset.route));
}
function go(route,params={}){const q=new URLSearchParams(params);location.hash=`${route}${q.size?'?'+q:''}`}
function setTitle(kicker,title){$('#page-kicker').textContent=kicker;$('#page-title').textContent=title;document.title=`${title} — TKA Cerdas`}
function routeFromHash(){const raw=location.hash.slice(1)||'dashboard';const [route,q='']=raw.split('?');state.route=route;state.params=new URLSearchParams(q);renderNav();renderRoute();$('.sidebar')?.classList.remove('open')}
async function q(table,select='*',builder=x=>x){const {data,error}=await builder(supabase.from(table).select(select));if(error)throw error;return data||[]}
function statCard(label,value,note,icon){return `<div class="stat-card"><div class="stat-top"><span>${label}</span><span class="stat-icon">${icon}</span></div><div class="stat-value">${value}</div><div class="stat-note">${note}</div></div>`}

async function dashboard(){
  setTitle('RUANG BELAJAR','Beranda');$('#view').innerHTML=skeleton();
  try{
    const [summaryRows,mastery,history,active]=await Promise.all([q('student_dashboard_summary','*'),q('student_mastery','*',x=>x.order('mastery_score',{ascending:false})),q('attempt_history','*',x=>x.order('completed_at',{ascending:false}).limit(5)),q('attempts','id,type,started_at,expires_at',x=>x.eq('status','in_progress').gt('expires_at',new Date().toISOString()).order('started_at',{ascending:false}).limit(1))]);
    const s=summaryRows[0]||{};const weak=[...mastery].sort((a,b)=>a.mastery_score-b.mastery_score)[0];const avg=Math.round(s.average_score||0);
    $('#streak-count').textContent=s.study_streak||0;
    $('#view').innerHTML=`${active.length?`<div class="inline-notice" style="margin-bottom:1rem;display:flex;justify-content:space-between;align-items:center;gap:1rem"><span>Kamu memiliki pengerjaan yang belum selesai.</span><button class="button primary compact" data-resume="${active[0].id}">Lanjutkan →</button></div>`:''}<div class="hero-strip"><div><p class="eyebrow">REKOMENDASI HARI INI</p><h2>Halo, ${esc(state.profile.full_name.split(' ')[0])}. ${weak?`Perkuat <span>${esc(weak.topic_name)}</span> hari ini.`:'Mulai perjalanan TKA-mu hari ini.'}</h2><p>${weak?`Akurasi kamu ${Math.round(weak.mastery_score||0)}%. Latihan singkat akan membantu menemukan konsep yang masih perlu diperbaiki.`:'Pilih materi pertama lalu kerjakan latihan singkat untuk memetakan kemampuanmu.'}</p><div class="hero-actions">${weak?`<button class="button accent" data-practice="${weak.topic_id}">Latihan 5 soal →</button>`:''}<button class="button secondary" data-route="learn">Buka materi</button></div></div><div class="hero-score"><div class="score-ring" style="--value:${avg}"><strong>${avg}</strong></div><small>Rata-rata nilai</small></div></div>
    <div class="stats-grid">${statCard('Latihan selesai',s.practice_count||0,'Semua sesi latihan','✓')}${statCard('Mini tryout',s.mini_count||0,'Simulasi singkat','◫')}${statCard('Tryout',s.tryout_count||0,'Simulasi penuh','◷')}${statCard('Soal dijawab',s.questions_answered||0,'Total aktivitas','✎')}</div>
    <div class="content-grid"><div class="card"><div class="card-head"><div><h3>Penguasaan materi</h3><p>Diolah dari jawaban yang sudah kamu kerjakan.</p></div><button class="text-link" data-route="progress">Lihat detail</button></div>${mastery.length?`<div class="list">${mastery.slice(0,5).map(m=>`<div class="list-item"><div class="list-icon">${Math.round(m.mastery_score||0)}</div><div class="list-main"><b>${esc(m.topic_name)}</b><div class="progress-track"><div class="progress-bar" style="--value:${m.mastery_score||0}%"></div></div></div><span class="badge ${scoreBadge(m.mastery_score)}">${m.mastery_score>=80?'Kuat':m.mastery_score>=65?'Cukup':'Perlu latihan'}</span></div>`).join('')}</div>`:emptyState('◎','Belum ada peta kemampuan','Kerjakan latihan pertama untuk mulai mengukur penguasaan materi.')}</div>
    <div class="card"><div class="card-head"><div><h3>Aktivitas terbaru</h3><p>Sesi yang baru diselesaikan.</p></div></div>${history.length?`<div class="list">${history.map(a=>`<button class="list-item" data-result="${a.id}"><div class="list-icon">${Math.round(a.score||0)}</div><div class="list-main"><b>${esc(a.display_name)}</b><small>${fmtDate(a.completed_at)}</small></div><span class="badge ${scoreBadge(a.score)}">${Math.round(a.score||0)}</span></button>`).join('')}</div>`:emptyState('◷','Belum ada riwayat','Aktivitas yang selesai akan tampil di sini.')}</div></div>`;
    bindCommon(); $$('[data-practice]').forEach(b=>b.onclick=()=>showPracticeChoice(b.dataset.practice));$$('[data-result]').forEach(b=>b.onclick=()=>go('result',{id:b.dataset.result}));$$('[data-resume]').forEach(b=>b.onclick=()=>go('attempt',{id:b.dataset.resume}));
  }catch(e){showError(e)}
}

async function learn(){
  setTitle('MATERI & LATIHAN','Belajar');$('#view').innerHTML=skeleton();
  try{const subjects=await q('subjects','id,name,code,description',x=>x.eq('status','active').order('sort_order'));$('#view').innerHTML=`<div class="section-title"><div><h2>Pilih mata pelajaran</h2><p>Pelajari konsep, lalu ukur pemahaman melalui latihan per materi.</p></div></div>${subjects.length?`<div class="subject-grid">${subjects.map(s=>`<button class="subject-card" data-subject="${s.id}"><div class="subject-code">${esc(s.code.slice(0,3))}</div><h3>${esc(s.name)}</h3><p>${esc(s.description||'Materi dan latihan TKA')}</p><span class="text-link">Buka mata pelajaran →</span></button>`).join('')}</div>`:emptyState('▤','Materi belum tersedia','Guru belum mengaktifkan mata pelajaran.')}`;$$('[data-subject]').forEach(b=>b.onclick=()=>go('topics',{subject:b.dataset.subject}))}catch(e){showError(e)}
}
async function topics(){
  setTitle('MATERI & LATIHAN','Daftar Materi');$('#view').innerHTML=skeleton();const subject=state.params.get('subject');
  try{const [subs,topics]=await Promise.all([q('subjects','name,description',x=>x.eq('id',subject).single()),q('topics','id,name,description,sort_order',x=>x.eq('subject_id',subject).eq('status','active').order('sort_order'))]);const s=Array.isArray(subs)?subs[0]:subs;$('#view').innerHTML=`<button class="text-link" data-route="learn">← Mata pelajaran</button><div class="section-title"><div><h2>${esc(s?.name||'Materi')}</h2><p>${esc(s?.description||'Pilih materi untuk mulai belajar atau latihan.')}</p></div></div><div class="topic-list">${topics.map((t,i)=>`<div class="topic-card"><span class="topic-number">${i+1}</span><div class="list-main"><h3>${esc(t.name)}</h3><small>${esc(t.description||'')}</small></div><div class="topic-actions"><button class="button secondary compact" data-material="${t.id}">Belajar</button><button class="button primary compact" data-practice="${t.id}">Latihan</button></div></div>`).join('')}</div>`;bindCommon();$$('[data-material]').forEach(b=>b.onclick=()=>go('material',{topic:b.dataset.material}));$$('[data-practice]').forEach(b=>b.onclick=()=>showPracticeChoice(b.dataset.practice))}catch(e){showError(e)}
}
async function material(){
  setTitle('MATERI & LATIHAN','Baca Materi');$('#view').innerHTML=skeleton();const topic=state.params.get('topic');
  try{const mats=await q('learning_materials','id,title,content,topic_id,topics(name,subject_id)',x=>x.eq('topic_id',topic).eq('status','active').order('sort_order'));const m=mats[0];if(!m){$('#view').innerHTML=emptyState('▤','Materi belum tersedia','Guru belum menerbitkan materi ini.');return}$('#view').innerHTML=`<div class="reading"><button class="text-link" onclick="history.back()">← Kembali</button><article class="card"><p class="eyebrow navy">${esc(m.topics?.name||'MATERI TKA')}</p><h2>${esc(m.title)}</h2><div class="reading-content">${m.content}</div><div class="form-actions"><button class="button secondary" id="mark-learned">Tandai sudah dipelajari</button><button class="button primary" data-practice="${m.topic_id}">Mulai latihan →</button></div></article></div>`;$('#mark-learned').onclick=async()=>{const {error}=await supabase.rpc('mark_material_complete',{p_material_id:m.id});if(error)toast(error.message,'error');else toast('Materi ditandai selesai')};$('[data-practice]').onclick=()=>showPracticeChoice(m.topic_id)}catch(e){showError(e)}
}
function showPracticeChoice(topicId){openModal(`<h2>Mulai latihan</h2><p>Pilih jumlah soal. Sistem memprioritaskan soal baru dan soal yang sebelumnya salah.</p><div class="choice-grid" style="margin-top:1rem">${[5,10,15].map(n=>`<button class="choice-button" data-count="${n}"><b>${n}</b>soal</button>`).join('')}</div><div class="form-actions"><button class="button secondary" id="cancel-start">Batal</button></div>`);$('#cancel-start').onclick=closeModal;$$('[data-count]').forEach(b=>b.onclick=()=>startAttempt({type:'practice',topic_id:topicId,question_count:+b.dataset.count}))}
async function assessmentList(type){
  const isMini=type==='mini_tryout';setTitle('SIMULASI TKA',isMini?'Mini Tryout':'Tryout');$('#view').innerHTML=skeleton();
  try{const table=isMini?'mini_tryouts':'tryouts';const items=await q(table,'id,name,description,question_count,duration_minutes,max_attempts,start_at,end_at',x=>x.eq('status','active').order('created_at',{ascending:false}));$('#view').innerHTML=`<div class="section-title"><div><h2>${isMini?'Latihan lintas materi':'Simulasi TKA lengkap'}</h2><p>${isMini?'Soal diacak berdasarkan komposisi materi yang telah ditetapkan.':'Kerjakan seperti ujian sebenarnya. Perhatikan durasi dan kesempatan.'}</p></div></div>${items.length?`<div class="subject-grid">${items.map(x=>`<div class="subject-card"><div class="subject-code">${isMini?'MT':'TO'}</div><h3>${esc(x.name)}</h3><p>${esc(x.description||'')}</p><div class="filter-pills"><span class="badge neutral">${x.question_count} soal</span><span class="badge neutral">${x.duration_minutes} menit</span>${x.max_attempts?`<span class="badge neutral">${x.max_attempts}× kesempatan</span>`:''}</div><button class="button primary wide" style="margin-top:1rem" data-assessment="${x.id}">Mulai <span>→</span></button></div>`).join('')}</div>`:emptyState('◫','Belum ada jadwal','Guru belum mengaktifkan '+(isMini?'mini tryout.':'tryout.'))}`;$$('[data-assessment]').forEach(b=>b.onclick=()=>confirmAssessment(type,b.dataset.assessment,items.find(x=>x.id===b.dataset.assessment)))}catch(e){showError(e)}
}
function confirmAssessment(type,id,item){openModal(`<h2>${esc(item.name)}</h2><div class="inline-notice">Timer dimulai setelah tombol di bawah ditekan. Jawaban tersimpan otomatis dan tes dikirim otomatis ketika waktu habis.</div><div class="stats-grid" style="grid-template-columns:1fr 1fr;margin-top:1rem">${statCard('Jumlah soal',item.question_count,'Sesuai blueprint','✎')}${statCard('Durasi',item.duration_minutes+' menit','Gunakan waktu dengan baik','◷')}</div><div class="form-actions"><button class="button secondary" id="cancel-start">Batal</button><button class="button primary" id="confirm-start">Mulai sekarang</button></div>`);$('#cancel-start').onclick=closeModal;$('#confirm-start').onclick=()=>startAttempt({type,[type==='mini_tryout'?'mini_tryout_id':'tryout_id']:id})}
async function startAttempt(payload){const button=$('#confirm-start')||$('[data-count]');try{setLoading(button,true,'Menyiapkan soal…');const data=await invoke('start-attempt',payload);closeModal();go('attempt',{id:data.attempt_id})}catch(e){toast(e.message,'error');setLoading(button,false)}}
async function attempt(){
  setTitle('SESI PENGERJAAN','Kerjakan Soal');$('#view').innerHTML=skeleton();clearInterval(state.timer);
  try{state.attempt=await invoke('get-attempt',{attempt_id:state.params.get('id')});state.current=0;if(state.attempt.status==='completed'){go('result',{id:state.attempt.id});return}renderQuestion();startTimer()}catch(e){showError(e)}
}
function renderQuestion(){const a=state.attempt,q=a.questions[state.current];const selected=q.selected_option;$('#view').innerHTML=`<div class="assessment-layout"><div class="card question-card"><div class="question-meta"><span>Soal ${state.current+1} dari ${a.questions.length}</span><button class="text-link" id="flag-question">${q.is_flagged?'★ Ditandai':'☆ Tandai soal'}</button></div><div class="question-text">${esc(q.question_text)}</div>${q.image_url?`<img class="question-image" src="${esc(q.image_url)}" alt="Ilustrasi soal">`:''}<div class="options">${q.options.map(o=>`<button class="option ${selected===o.key?'selected':''}" data-option="${o.key}"><span class="option-letter">${o.key}</span><span>${esc(o.text)}</span></button>`).join('')}</div><div class="question-footer"><button class="button secondary" id="prev-question" ${state.current===0?'disabled':''}>← Sebelumnya</button><button class="button secondary" id="finish-attempt">Selesaikan</button><button class="button primary" id="next-question">${state.current===a.questions.length-1?'Periksa jawaban':'Berikutnya →'}</button></div></div><aside class="card navigator-card"><div class="timer" id="timer">--:--</div><h3>Navigasi soal</h3><div class="number-grid" style="margin-top:.8rem">${a.questions.map((x,i)=>`<button class="number-button ${x.selected_option?'answered':''} ${x.is_flagged?'flagged':''} ${i===state.current?'current':''}" data-number="${i}">${i+1}</button>`).join('')}</div><div class="save-status" id="save-status">Semua jawaban tersimpan</div></aside></div>`;
  $$('[data-option]').forEach(b=>b.onclick=()=>saveAnswer(q.id,b.dataset.option));$$('[data-number]').forEach(b=>b.onclick=()=>{state.current=+b.dataset.number;renderQuestion()});$('#prev-question').onclick=()=>{state.current--;renderQuestion()};$('#next-question').onclick=()=>{if(state.current<a.questions.length-1){state.current++;renderQuestion()}else confirmSubmit()};$('#finish-attempt').onclick=confirmSubmit;$('#flag-question').onclick=()=>saveAnswer(q.id,q.selected_option,!q.is_flagged)
}
async function saveAnswer(attemptQuestionId,option,flagged){const q=state.attempt.questions.find(x=>x.id===attemptQuestionId);q.selected_option=option||null;if(typeof flagged==='boolean')q.is_flagged=flagged;renderQuestion();$('#save-status').textContent='Menyimpan…';const {error}=await supabase.rpc('save_answer',{p_attempt_question_id:attemptQuestionId,p_selected_option:q.selected_option,p_is_flagged:q.is_flagged});if(error){$('#save-status').textContent='Gagal menyimpan';toast('Jawaban belum tersimpan. Periksa koneksi.','error')}else $('#save-status').textContent='Jawaban tersimpan'}
function startTimer(){const tick=()=>{const end=new Date(state.attempt.expires_at).getTime(),left=Math.max(0,Math.ceil((end-Date.now())/1000));const el=$('#timer');if(el)el.textContent=fmtDuration(left);if(left<=0){clearInterval(state.timer);submitAttempt(true)}};tick();state.timer=setInterval(tick,1000)}
function confirmSubmit(){const unanswered=state.attempt.questions.filter(q=>!q.selected_option).length;openModal(`<h2>Selesaikan pengerjaan?</h2><p>${unanswered?`Masih ada <b>${unanswered} soal</b> yang belum dijawab.`:'Semua soal sudah dijawab.'} Setelah dikirim, jawaban tidak dapat diubah.</p><div class="form-actions"><button class="button secondary" id="cancel-submit">Periksa lagi</button><button class="button primary" id="confirm-submit">Kirim jawaban</button></div>`);$('#cancel-submit').onclick=closeModal;$('#confirm-submit').onclick=()=>submitAttempt(false)}
async function submitAttempt(auto=false){try{setLoading($('#confirm-submit'),true,'Menilai…');const data=await invoke('submit-attempt',{attempt_id:state.attempt.id,auto_submit:auto});clearInterval(state.timer);closeModal();go('result',{id:data.attempt_id})}catch(e){toast(e.message,'error');setLoading($('#confirm-submit'),false)}}
async function result(){
  setTitle('HASIL & PEMBAHASAN','Hasil Pengerjaan');$('#view').innerHTML=skeleton();
  try{const data=await invoke('get-attempt',{attempt_id:state.params.get('id'),include_review:true});$('#view').innerHTML=`<div class="card result-hero"><p class="eyebrow navy">${esc(data.display_name)}</p><div class="result-score">${Math.round(data.score||0)}</div><p>Nilai akhir</p><div class="result-breakdown"><span>✓ ${data.correct_count} benar</span><span>× ${data.wrong_count} salah</span><span>◷ ${fmtDuration(data.duration_seconds)}</span></div><div class="hero-actions" style="justify-content:center"><button class="button secondary" data-route="history">Lihat riwayat</button><button class="button primary" data-route="learn">Belajar lagi</button></div></div><div class="section-title"><div><h2>Pembahasan soal</h2><p>Pelajari alasan di balik setiap jawaban.</p></div></div>${data.questions.map((x,i)=>`<article class="review-item ${x.is_correct?'correct':'wrong'}"><h3>${i+1}. ${x.question_text}</h3><p>Jawaban kamu: <b>${x.selected_option||'Tidak dijawab'}</b> · Jawaban benar: <b>${x.correct_option}</b></p><div class="explanation"><b>Pembahasan</b><br>${x.explanation||'Pembahasan belum tersedia.'}</div></article>`).join('')}`;bindCommon()}catch(e){showError(e)}
}
async function progress(){
  setTitle('ANALISIS BELAJAR','Progres Saya');$('#view').innerHTML=skeleton();
  try{const [mastery,trend]=await Promise.all([q('student_mastery','*',x=>x.order('mastery_score',{ascending:false})),q('attempt_history','id,display_name,score,completed_at',x=>x.limit(12).order('completed_at',{ascending:true}))]);const weak=[...mastery].sort((a,b)=>a.mastery_score-b.mastery_score)[0];$('#view').innerHTML=`${weak?`<div class="hero-strip"><div><p class="eyebrow">FOKUS BERIKUTNYA</p><h2>Perkuat <span>${esc(weak.topic_name)}</span></h2><p>Penguasaan saat ini ${Math.round(weak.mastery_score)}% dari ${weak.total_answered} jawaban. Ulangi materi, lalu coba 5 soal baru.</p><div class="hero-actions"><button class="button accent" data-practice="${weak.topic_id}">Latihan sekarang →</button></div></div><div class="hero-score"><div class="score-ring" style="--value:${weak.mastery_score}"><strong>${Math.round(weak.mastery_score)}</strong></div><small>Penguasaan</small></div></div>`:''}<div class="content-grid" style="margin-top:1rem"><div class="card"><div class="card-head"><div><h3>Tren nilai</h3><p>${trend.length} pengerjaan terakhir.</p></div></div>${trend.length?`<div class="chart-bars">${trend.map((t,i)=>`<div class="bar-wrap" title="${esc(t.display_name)}: ${Math.round(t.score)}"><div class="bar" style="--value:${t.score}"></div><small>${i+1}</small></div>`).join('')}</div>`:emptyState('↗','Belum ada tren','Selesaikan minimal satu latihan.')}</div><div class="card"><div class="card-head"><div><h3>Peta kemampuan</h3><p>Per materi</p></div></div><div class="list">${mastery.map(m=>`<div class="list-item"><div class="list-main"><b>${esc(m.topic_name)}</b><small>${m.correct_count}/${m.total_answered} benar</small><div class="progress-track"><div class="progress-bar" style="--value:${m.mastery_score}%"></div></div></div><b>${Math.round(m.mastery_score)}%</b></div>`).join('')}</div></div></div>`;$$('[data-practice]').forEach(b=>b.onclick=()=>showPracticeChoice(b.dataset.practice))}catch(e){showError(e)}
}
async function historyView(){
  setTitle('AKTIVITAS BELAJAR','Riwayat');$('#view').innerHTML=skeleton();
  try{const rows=await q('attempt_history','*',x=>x.limit(100));$('#view').innerHTML=`<div class="toolbar"><div><h2>Riwayat pengerjaan</h2><p>Semua latihan dan simulasi yang telah diselesaikan.</p></div><div class="filter-pills"><button class="filter-pill active" data-filter="all">Semua</button><button class="filter-pill" data-filter="practice">Latihan</button><button class="filter-pill" data-filter="mini_tryout">Mini</button><button class="filter-pill" data-filter="tryout">Tryout</button></div></div><div id="history-table"></div>`;const draw=f=>{$('#history-table').innerHTML=rows.filter(r=>f==='all'||r.type===f).length?`<div class="table-wrap"><table class="data-table"><thead><tr><th>Aktivitas</th><th>Tanggal</th><th>Soal</th><th>Durasi</th><th>Nilai</th><th></th></tr></thead><tbody>${rows.filter(r=>f==='all'||r.type===f).map(r=>`<tr><td><b>${esc(r.display_name)}</b><br><small>${esc(r.type.replace('_',' '))}</small></td><td>${fmtDate(r.completed_at)}</td><td>${r.correct_count}/${r.total_questions} benar</td><td>${fmtDuration(r.duration_seconds)}</td><td><span class="badge ${scoreBadge(r.score)}">${Math.round(r.score)}</span></td><td><button class="button secondary compact" data-result="${r.id}">Detail</button></td></tr>`).join('')}</tbody></table></div>`:emptyState('≡','Belum ada riwayat','Belum ada aktivitas pada kategori ini.')};draw('all');$$('[data-filter]').forEach(b=>b.onclick=()=>{$$('[data-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');draw(b.dataset.filter);$$('[data-result]').forEach(x=>x.onclick=()=>go('result',{id:x.dataset.result}))});$$('[data-result]').forEach(x=>x.onclick=()=>go('result',{id:x.dataset.result}))}catch(e){showError(e)}
}
function bindCommon(){$$('[data-route]').forEach(el=>el.onclick=()=>go(el.dataset.route))}
function showError(e){console.error(e);$('#view').innerHTML=emptyState('!','Data belum dapat dimuat',e.message||'Periksa koneksi lalu coba lagi.',`<button class="button primary" onclick="location.reload()">Coba lagi</button>`)}
async function renderRoute(){clearInterval(state.timer);const routes={dashboard,learn,topics,material,mini:()=>assessmentList('mini_tryout'),tryout:()=>assessmentList('tryout'),attempt,result,progress,history:historyView};(routes[state.route]||dashboard)();}
async function boot(){setupModal();setupSidebar();$('#toggle-password').onclick=()=>{const i=$('#login-password');i.type=i.type==='password'?'text':'password'};$('#login-form').onsubmit=async e=>{e.preventDefault();const b=e.submitter;setLoading(b,true,'Memeriksa…');const {error}=await login($('#login-username').value,$('#login-password').value);if(error){$('#login-error').textContent='Username atau password salah.';$('#login-error').classList.remove('hidden');setLoading(b,false)}else location.reload()};if(!isConfigured){$('#login-error').textContent='Aplikasi belum dikonfigurasi. Ikuti README untuk menghubungkan Supabase.';$('#login-error').classList.remove('hidden');return}const auth=await requireSession(['student']);if(auth.error||!auth.session){if(auth.error&&auth.error.message.includes('izin'))$('#login-error').textContent=auth.error.message;return}state.profile=auth.profile;$('#auth-screen').classList.add('hidden');$('#app-shell').classList.remove('hidden');const name=auth.profile.full_name,init=initials(name);$('#sidebar-name').textContent=name;$('#sidebar-class').textContent=auth.profile.classes?.name||'Siswa';$('#sidebar-initial').textContent=init;$('#profile-button').textContent=init;$('#logout-button').onclick=logout;window.addEventListener('hashchange',routeFromHash);routeFromHash()}
boot();
